name: Deploy

on:
  push:
    branches: [main, development]
  workflow_dispatch:

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.branch-name.outputs.current_branch }}
    steps:
      - uses: actions/checkout@v3

      - name: Notify start
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            The ${{ github.event_name }} event on ${{ github.event.repository.name }}/${{ github.ref }} triggered the ${{ github.workflow }}.

  main:
    name: Build & Deploy
    needs: checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy files to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: ./
          targed: project